import = [
"~/.config/alacritty/catppuccin-mocha.toml"
]
[window]
opacity = 0.90

[font]
size = 10
[font.normal]
family = "Hack Nerd Font Mono"
style = "Regular"
[font.bold]
family = "Hack Nerd Font Mono"
style = "Bold"
[font.bold_italic]
family = "Hack Nerd Font Mono"
style = "Bold Italic"
[font.italic]
family = "Hack Nerd Font Mono"
style = "Italic"

[env]
TERM = "xterm-256color"
